`timescale 1ns/1ps
module tb_tp5_integration;localparam CPB=4;reg clk=0,pi_signal=0,i2s_sd=0,uart_rx=1;wire i2s_sck,i2s_ws,led,uart_tx;integer fails=0,i;reg[7:0]rxbytes[0:11];reg[7:0]crc;always #5 clk=~clk;
safe_field_tp5_top #(.POR_BITS(3),.HALF_PERIOD_CLKS(2),.WINDOW_LOG2(2),.THRESHOLD_ON(24'd10),.THRESHOLD_OFF(24'd5),.ATTACK_WINDOWS(1),.RELEASE_WINDOWS(1),.UART_CLKS_PER_BIT(CPB))dut(.sys_clk(clk),.pi_signal(pi_signal),.i2s_sd(i2s_sd),.uart_rx(uart_rx),.i2s_sck(i2s_sck),.i2s_ws(i2s_ws),.led(led),.uart_tx(uart_tx));
function[7:0]crc8_next;input[7:0]current,inputv;integer k;reg[7:0]c;begin c=current^inputv;for(k=0;k<8;k=k+1)c=c[7]?((c<<1)^8'h07):(c<<1);crc8_next=c;end endfunction
task send_byte;input[7:0]v;integer k;begin uart_rx=0;repeat(CPB)@(posedge clk);for(k=0;k<8;k=k+1)begin uart_rx=v[k];repeat(CPB)@(posedge clk);end uart_rx=1;repeat(CPB)@(posedge clk);end endtask
task send_cmd;input[7:0]c;input[15:0]s;input[31:0]p;reg[7:0]cc;begin cc=0;cc=crc8_next(cc,8'h05);cc=crc8_next(cc,c);cc=crc8_next(cc,s[15:8]);cc=crc8_next(cc,s[7:0]);cc=crc8_next(cc,p[31:24]);cc=crc8_next(cc,p[23:16]);cc=crc8_next(cc,p[15:8]);cc=crc8_next(cc,p[7:0]);send_byte(8'hA6);send_byte(8'h6A);send_byte(8'h05);send_byte(c);send_byte(s[15:8]);send_byte(s[7:0]);send_byte(p[31:24]);send_byte(p[23:16]);send_byte(p[15:8]);send_byte(p[7:0]);send_byte(cc);end endtask
task recv_byte;output[7:0]v;integer k;begin @(negedge uart_tx);repeat(CPB/2)@(posedge clk);repeat(CPB)@(posedge clk);for(k=0;k<8;k=k+1)begin repeat(CPB)@(posedge clk);v[k]=uart_tx;end repeat(CPB)@(posedge clk);end endtask
initial begin $dumpfile("build/tb_tp5_integration.vcd");$dumpvars(0,tb_tp5_integration);repeat(20)@(posedge clk);pi_signal=1;#1;if(led!==1'b1)begin $display("FAIL gpio17 observability");fails=fails+1;end pi_signal=0;fork begin send_cmd(8'h01,16'h0042,32'h0);end begin for(i=0;i<12;i=i+1)recv_byte(rxbytes[i]);end join if(rxbytes[0]!==8'h5A||rxbytes[1]!==8'hA5||rxbytes[2]!==8'h05||rxbytes[3]!==8'h01||rxbytes[4]!==8'h00||rxbytes[5]!==8'h42)begin $display("FAIL response header/type/sequence");fails=fails+1;end if({rxbytes[6],rxbytes[7],rxbytes[8],rxbytes[9]}!==32'h54503501)begin $display("FAIL ping payload");fails=fails+1;end crc=0;for(i=2;i<=10;i=i+1)crc=crc8_next(crc,rxbytes[i]);if(crc!==rxbytes[11])begin $display("FAIL response CRC got=%h expected=%h",rxbytes[11],crc);fails=fails+1;end if(fails==0)$display("TEST_RESULT: PASS tp5_integration");else $display("TEST_RESULT: FAIL tp5_integration fails=%0d",fails);$finish(fails!=0);end
endmodule
