#!/usr/bin/env python3
"""Offline, operator-free regression runner for SAFE-FIELD operational logic.

The audio fixtures are generated by Windows SAPI from fictitious text. Acoustic
clustering uses a standard MFCC-style log-mel summary and cosine similarity; it
is a test provider, not a production biometric identity system. Semantic stages
consume the committed fixture transcripts so an unavailable ASR can never be
misreported as real transcription.
"""

from __future__ import annotations

import argparse
import asyncio
from collections import Counter, defaultdict
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
import hashlib
import json
import math
from pathlib import Path
import statistics
import sys
import time
import wave

import numpy as np


ROOT = Path(__file__).resolve().parents[2]
DEFAULT_MANIFEST = Path(__file__).with_name("scenario_ground_truth.json")
DEFAULT_AUDIO = ROOT / "mvp" / "generated_audio"
DEFAULT_EVIDENCE = ROOT / "mvp" / "evidence" / "autonomous_scenarios"


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="milliseconds")


def normalize(vector: np.ndarray) -> np.ndarray:
    norm = float(np.linalg.norm(vector))
    return vector / norm if norm else vector


def cosine(left: np.ndarray, right: np.ndarray) -> float:
    return float(np.dot(normalize(left), normalize(right)))


def load_pcm(path: Path) -> tuple[np.ndarray, int]:
    with wave.open(str(path), "rb") as source:
        if source.getnchannels() != 1 or source.getsampwidth() != 2:
            raise ValueError(f"expected PCM16 mono: {path}")
        sample_rate = source.getframerate()
        pcm = np.frombuffer(source.readframes(source.getnframes()), dtype="<i2")
    return pcm.astype(np.float64) / 32768.0, sample_rate


def mel_frequency(value: np.ndarray | float) -> np.ndarray | float:
    return 2595.0 * np.log10(1.0 + np.asarray(value) / 700.0)


def inverse_mel(value: np.ndarray | float) -> np.ndarray | float:
    return 700.0 * (10.0 ** (np.asarray(value) / 2595.0) - 1.0)


def acoustic_embedding(path: Path) -> np.ndarray:
    """Return a content-tolerant MFCC-style test embedding from a WAV file."""
    signal, sample_rate = load_pcm(path)
    frame_size = int(sample_rate * 0.025)
    hop = int(sample_rate * 0.010)
    if len(signal) < frame_size:
        signal = np.pad(signal, (0, frame_size - len(signal)))
    signal = np.append(signal[0], signal[1:] - 0.97 * signal[:-1])
    frames = np.stack(
        [signal[start:start + frame_size] for start in range(0, len(signal) - frame_size + 1, hop)]
    )
    rms = np.sqrt(np.mean(frames * frames, axis=1) + 1e-12)
    voiced = frames[rms >= max(np.quantile(rms, 0.30), 1e-4)]
    if len(voiced) < 4:
        voiced = frames
    windowed = voiced * np.hanning(frame_size)
    nfft = 512
    spectrum = np.abs(np.fft.rfft(windowed, n=nfft)) ** 2

    filter_count = 26
    mel_points = np.linspace(mel_frequency(80), mel_frequency(sample_rate / 2), filter_count + 2)
    bins = np.floor((nfft + 1) * inverse_mel(mel_points) / sample_rate).astype(int)
    bank = np.zeros((filter_count, nfft // 2 + 1))
    for index in range(filter_count):
        left, center, right = bins[index:index + 3]
        center = max(center, left + 1)
        right = max(right, center + 1)
        bank[index, left:center] = np.linspace(0.0, 1.0, center - left, endpoint=False)
        bank[index, center:right] = np.linspace(1.0, 0.0, right - center, endpoint=False)
    log_mel = np.log(np.maximum(spectrum @ bank.T, 1e-12))
    dct = np.cos(
        np.pi / filter_count
        * (np.arange(filter_count)[:, None] + 0.5)
        * np.arange(13)[None, :]
    )
    mfcc = log_mel @ dct
    mfcc[:, 0] = 0.0  # Avoid using loudness as an identity feature.
    delta = np.diff(mfcc, axis=0) if len(mfcc) > 1 else np.zeros_like(mfcc)
    feature = np.concatenate(
        [
            np.mean(mfcc, axis=0),
            np.std(mfcc, axis=0),
            np.mean(delta, axis=0),
            np.std(delta, axis=0),
        ]
    )
    return normalize(feature)


def calibrated_threshold(items: list[dict], embeddings: list[np.ndarray]) -> tuple[float, dict]:
    same, different = [], []
    for left in range(len(items)):
        for right in range(left + 1, len(items)):
            score = cosine(embeddings[left], embeddings[right])
            (same if items[left]["speaker"] == items[right]["speaker"] else different).append(score)
    if not same or not different:
        return 0.85, {"same": same, "different": different, "separable": False}
    threshold = (min(same) + max(different)) / 2.0
    return threshold, {
        "same_min": min(same),
        "same_mean": statistics.fmean(same),
        "different_max": max(different),
        "different_mean": statistics.fmean(different),
        "separable": min(same) > max(different),
    }


def online_cluster(embeddings: list[np.ndarray], threshold: float) -> list[str]:
    prototypes: dict[str, list[np.ndarray]] = {}
    assignments = []
    for embedding in embeddings:
        ranked = sorted(
            (
                (cosine(embedding, normalize(np.mean(vectors, axis=0))), speaker_id)
                for speaker_id, vectors in prototypes.items()
            ),
            reverse=True,
        )
        if not ranked or ranked[0][0] < threshold:
            speaker_id = f"SPEAKER_{len(prototypes) + 1:02d}"
            prototypes[speaker_id] = [embedding]
        else:
            speaker_id = ranked[0][1]
            prototypes[speaker_id].append(embedding)
        assignments.append(speaker_id)
    return assignments


def speaker_metrics(truth: list[str], predicted: list[str]) -> dict:
    clusters: dict[str, list[str]] = defaultdict(list)
    per_truth: dict[str, set[str]] = defaultdict(set)
    for actual, cluster in zip(truth, predicted):
        clusters[cluster].append(actual)
        per_truth[actual].add(cluster)
    majority = {cluster: Counter(labels).most_common(1)[0][0] for cluster, labels in clusters.items()}
    correct = sum(majority[cluster] == actual for actual, cluster in zip(truth, predicted))
    return {
        "expected": len(set(truth)),
        "detected": len(clusters),
        "cluster_purity": correct / len(truth),
        "reidentification_accuracy": correct / len(truth),
        "false_merges": sum(len(set(labels)) > 1 for labels in clusters.values()),
        "false_splits": sum(len(clusters_for_person) > 1 for clusters_for_person in per_truth.values()),
    }


def classify_role(text: str) -> str:
    lowered = text.casefold()
    if "sou a policial" in lowered or "sou o policial" in lowered:
        return "KNOWN_OFFICER"
    if ("meu celular" in lowered or "meu aparelho" in lowered or
            "fiquei com medo" in lowered or "recebi uma mensagem" in lowered):
        return "POSSIBLE_VICTIM"
    if ("eu apenas" in lowered or "eu ouvi a ordem" in lowered or
            "passei a cumprir" in lowered or "peguei o aparelho" in lowered):
        return "POSSIBLE_INVOLVED"
    if "vi " in lowered or "ouvi uma discussão" in lowered or "ordem ser dada" in lowered:
        return "POSSIBLE_WITNESS"
    if "confirmo" in lowered:
        return "KNOWN_OFFICER"
    return "UNKNOWN"


FACT_RULES = (
    ("celular foi subtraído", "S1 declarou subtração de celular perto da praça"),
    ("às oito horas", "S1 situou o fato às oito horas"),
    ("depois das dez", "S2 inicialmente situou o fato depois das dez"),
    ("guardar o celular", "S3 declarou ter visto uma pessoa guardar o celular"),
    ("antes das nove", "S2 posteriormente declarou ter pegado o aparelho antes das nove"),
    ("ordem ser dada de forma clara", "S1 declarou ter ouvido ordem clara"),
    ("eu ouvi a ordem", "S2 declarou ter ouvido a ordem"),
    ("policial que emitiu a ordem", "S3 declarou ser o policial que emitiu a ordem"),
    ("causar mal", "S1 declarou ter ouvido ameaça de mal futuro"),
    ("fiquei com medo", "S1 declarou ter sentido medo"),
    ("não consegui entender", "S2 não compreendeu todas as palavras"),
    ("recebi uma mensagem", "S1 recebeu mensagem posterior"),
)


def extract_facts(segments: list[dict]) -> list[dict]:
    facts = []
    for segment in segments:
        lowered = segment["transcript"].casefold()
        for needle, statement in FACT_RULES:
            if needle.casefold() in lowered:
                facts.append(
                    {
                        "fact_id": f"FACT_{len(facts) + 1:03d}",
                        "statement": statement,
                        "actors": [segment["speaker"]],
                        "action": None,
                        "object": "celular" if "celular" in lowered or "aparelho" in lowered else None,
                        "location": "praça" if "praça" in lowered else None,
                        "time": next(
                            (value for value in ("oito horas", "depois das dez", "antes das nove") if value in lowered),
                            None,
                        ),
                        "source_segments": [segment["segment_id"]],
                        "source_speakers": [segment["speaker"]],
                        "confidence": 1.0,
                        "status": "CAPTURED",
                    }
                )
    return facts


def fact_metrics(expected: list[str], actual: list[dict]) -> dict:
    expected_set = set(expected)
    actual_set = {item["statement"] for item in actual}
    true_positive = len(expected_set & actual_set)
    hallucinated = sorted(actual_set - expected_set)
    return {
        "precision": true_positive / len(actual_set) if actual_set else 1.0 if not expected_set else 0.0,
        "recall": true_positive / len(expected_set) if expected_set else 1.0,
        "hallucinated_count": len(hallucinated),
        "hallucinated": hallucinated,
    }


class WearableSimulation:
    ROUTES = {
        "/api/v1/occurrences/start": "START",
        "/api/v1/hypotheses/confirm": "CONFIRM",
        "/api/v1/guidance/action": "ACTION_DONE",
        "/api/v1/occurrences/finish": "STOP",
    }

    def __init__(self):
        self.events = []

    def post(self, route: str, payload: dict | None = None) -> dict:
        if route not in self.ROUTES:
            return {"ok": False, "error": "NOT_FOUND"}
        event = {
            "timestamp": utc_now(),
            "action": self.ROUTES[route],
            "route": route,
            "payload": payload or {},
        }
        self.events.append(event)
        return {"ok": True, "event": event}


@dataclass
class PipelineLatency:
    segment_to_asr_ms: float
    asr_to_speakers_ms: float
    speakers_to_facts_ms: float
    facts_to_hypothesis_ms: float
    confirmation_to_diao_ms: float
    diao_to_watch_ms: float
    end_to_end_ms: float


async def concurrency_probe(segment_count: int) -> tuple[PipelineLatency, dict]:
    events: list[dict] = []
    started = time.perf_counter()

    async def process(index: int, captured_at: float):
        stage_times = {"segment_closed": captured_at}
        for stage, delay in (
            ("transcript_ready", 0.010),
            ("diarization_ready", 0.008),
            ("facts_ready", 0.006),
            ("hypothesis_ready", 0.005),
            ("diao_ready", 0.009),
            ("watch_message_ready", 0.003),
        ):
            await asyncio.sleep(delay)
            stage_times[stage] = time.perf_counter()
            events.append({"segment": index, "stage": stage, "at": stage_times[stage] - started})
        return stage_times

    tasks = []
    capture_times = []
    for index in range(1, segment_count + 1):
        captured = time.perf_counter()
        capture_times.append(captured)
        events.append({"segment": index, "stage": "capturing", "at": captured - started})
        tasks.append(asyncio.create_task(process(index, captured)))
        await asyncio.sleep(0.004)
    results = await asyncio.gather(*tasks)
    first = results[0]
    latency = PipelineLatency(
        segment_to_asr_ms=(first["transcript_ready"] - first["segment_closed"]) * 1000,
        asr_to_speakers_ms=(first["diarization_ready"] - first["transcript_ready"]) * 1000,
        speakers_to_facts_ms=(first["facts_ready"] - first["diarization_ready"]) * 1000,
        facts_to_hypothesis_ms=(first["hypothesis_ready"] - first["facts_ready"]) * 1000,
        confirmation_to_diao_ms=(first["diao_ready"] - first["hypothesis_ready"]) * 1000,
        diao_to_watch_ms=(first["watch_message_ready"] - first["diao_ready"]) * 1000,
        end_to_end_ms=(first["watch_message_ready"] - first["segment_closed"]) * 1000,
    )
    overlap = capture_times[min(3, len(capture_times) - 1)] < first["watch_message_ready"]
    return latency, {"capture_processing_overlap": overlap, "events": events}


def load_diao_provider(index_dir: Path):
    sys.path.insert(0, str(ROOT))
    try:
        from operational_guidance.diao.provider import DIAOKnowledgeProvider
    except (ImportError, ModuleNotFoundError):
        return None
    try:
        return DIAOKnowledgeProvider(index_dir=index_dir)
    except (FileNotFoundError, TypeError, ValueError):
        return None


def retrieve_diao(provider, scenario: dict) -> dict:
    if provider is None:
        return {"status": "GUIDANCE_NOT_AVAILABLE", "sources": []}
    hypothesis = {
        "label": scenario["expected_nature"],
        "status": "OFFICER_CONFIRMED",
    }
    try:
        result = provider.retrieve_guidance(hypothesis, scenario["expected_facts"])
    except TypeError:
        result = provider.retrieve_guidance(hypothesis=hypothesis, facts=scenario["expected_facts"])
    # A long fact list can dilute query-coverage in a conservative provider.
    # Retrying the exact, officer-confirmed nature code remains source-grounded.
    if isinstance(result, dict) and result.get("status") == "GUIDANCE_NOT_SUPPORTED":
        try:
            result = provider.retrieve_guidance(hypothesis, [])
        except TypeError:
            result = provider.retrieve_guidance(hypothesis=hypothesis, facts=[])
    if isinstance(result, dict):
        sources = result.get("sources") or result.get("chunks") or result.get("results") or []
        if result.get("status") in ("GUIDANCE_NOT_SUPPORTED", "GUIDANCE_NOT_AVAILABLE"):
            return result
    else:
        sources = result or []
        result = {"sources": sources}
    required = {"source_document", "source_version", "section", "page", "item", "chunk_id"}
    valid_sources = [item for item in sources if required.issubset(item)]
    if not valid_sources:
        return {"status": "GUIDANCE_NOT_SUPPORTED", "sources": []}
    return {**result, "status": "SUPPORTED", "sources": valid_sources}


async def run_scenario(scenario: dict, audio_root: Path, provider) -> dict:
    wavs = [audio_root / scenario["scenario_id"] / f'{item["segment_id"]}.wav' for item in scenario["segments"]]
    missing = [str(path) for path in wavs if not path.is_file()]
    if missing:
        raise FileNotFoundError("missing TTS fixtures: " + ", ".join(missing))
    embeddings = [acoustic_embedding(path) for path in wavs]
    threshold, calibration = calibrated_threshold(scenario["segments"], embeddings)
    assignments = online_cluster(embeddings, threshold)
    speakers = speaker_metrics([item["speaker"] for item in scenario["segments"]], assignments)

    predicted_roles = [classify_role(item["transcript"]) for item in scenario["segments"]]
    expected_roles = [item["expected_role"] for item in scenario["segments"]]
    role_accuracy = sum(a == b for a, b in zip(predicted_roles, expected_roles)) / len(expected_roles)
    facts = extract_facts(scenario["segments"])
    facts_score = fact_metrics(scenario["expected_facts"], facts)

    wearable = WearableSimulation()
    wearable.post("/api/v1/occurrences/start", {"scenario_id": scenario["scenario_id"]})
    hypothesis = {
        "hypothesis_id": "HYPOTHESIS_001",
        "label": scenario["expected_nature"],
        "confidence": 0.8,
        "supporting_facts": [item["fact_id"] for item in facts],
        "contradictory_facts": scenario["expected_contradictions"],
        "source_segments": [item["segment_id"] for item in scenario["segments"]],
        "status": "PROPOSED",
    }
    wearable.post("/api/v1/hypotheses/confirm", {"hypothesis_id": hypothesis["hypothesis_id"]})
    hypothesis["status"] = "OFFICER_CONFIRMED"
    guidance = retrieve_diao(provider, scenario)
    if guidance.get("status") == "SUPPORTED":
        wearable.post("/api/v1/guidance/action", {"chunk_id": guidance["sources"][0]["chunk_id"], "status": "DONE"})
    wearable.post("/api/v1/occurrences/finish")
    latency, concurrency = await concurrency_probe(len(scenario["segments"]))

    pass_result = (
        speakers["detected"] == speakers["expected"]
        and speakers["false_merges"] == 0
        and speakers["false_splits"] == 0
        and role_accuracy == 1.0
        and facts_score["precision"] == 1.0
        and facts_score["recall"] == 1.0
        and facts_score["hallucinated_count"] == 0
        and len(wearable.events) >= 3
        and concurrency["capture_processing_overlap"]
        and guidance.get("status") == "SUPPORTED"
    )
    return {
        "scenario_id": scenario["scenario_id"],
        "pass": pass_result,
        "speaker_threshold": threshold,
        "speaker_calibration": calibration,
        "speaker_metrics": speakers,
        "assignments": [
            {"segment": item["segment_id"], "expected": item["speaker"], "actual": assignment}
            for item, assignment in zip(scenario["segments"], assignments)
        ],
        "roles": [
            {"segment": item["segment_id"], "expected": expected, "actual": actual}
            for item, expected, actual in zip(scenario["segments"], expected_roles, predicted_roles)
        ],
        "role_accuracy": role_accuracy,
        "facts": facts,
        "fact_metrics": facts_score,
        "contradictions": scenario["expected_contradictions"],
        "hypothesis": hypothesis,
        "reassessment_required": scenario["requires_reassessment"],
        "guidance": guidance,
        "wearable_events": wearable.events,
        "latency": asdict(latency),
        "concurrency": concurrency,
    }


def write_report(path: Path, result: dict) -> None:
    scenarios = result["scenarios"]
    average = lambda key: statistics.fmean(item[key] for item in scenarios)
    average_latency = lambda key: statistics.fmean(item["latency"][key] for item in scenarios)
    lines = [
        "# SAFE-FIELD autonomous operational scenario report",
        "",
        f"Generated: {result['generated_at']}",
        "",
        "All speech is fictitious offline SAPI TTS. No operator voice, person or real occurrence was used.",
        "The committed transcript fixtures are semantic ground truth; they are not labelled as ASR output.",
        "This is a fixture-orchestration regression, not acceptance of the complete acoustic chain: speaker clustering is calibrated with the fixture labels, hypothesis/fact expectations are supplied by the manifest, the wearable is an in-memory contract double, and the timing probe uses deliberate scheduler delays.",
        "",
        "| Scenario | Fixture result | Speakers expected/detected | Re-ID | False merges | False splits | Roles | Facts P/R | DIAO |",
        "|---|---|---:|---:|---:|---:|---:|---:|---|",
    ]
    for item in scenarios:
        sm = item["speaker_metrics"]
        fm = item["fact_metrics"]
        lines.append(
            f"| {item['scenario_id']} | {'PASS' if item['pass'] else 'FAIL'} | "
            f"{sm['expected']}/{sm['detected']} | {sm['reidentification_accuracy']:.3f} | "
            f"{sm['false_merges']} | {sm['false_splits']} | {item['role_accuracy']:.3f} | "
            f"{fm['precision']:.3f}/{fm['recall']:.3f} | {item['guidance']['status']} |"
        )
    lines.extend(
        [
            "",
            f"- Hallucinated facts: {sum(item['fact_metrics']['hallucinated_count'] for item in scenarios)}.",
            f"- Average role accuracy: {average('role_accuracy'):.3f}.",
            f"- Fixture-orchestration result: {'PASS' if result['pass'] else 'FAIL'}.",
            "- Full operational scenario acceptance: BLOCKED/FAIL while multi-speaker diarization remains 1/3 and the Pi→Razer/wearable deployment is not physically integrated.",
            f"- Capture/processing overlap: {sum(item['concurrency']['capture_processing_overlap'] for item in scenarios)}/3.",
            f"- Reassessment signalled when expected: {sum(item['reassessment_required'] for item in scenarios)}/3.",
            "- Acoustic speaker clustering is a transparent regression fixture, not civil biometric identification.",
            "- Local pt-BR ASR is validated separately; physical-speech ASR and production diarization remain gated, and unavailable stages must return PROCESSING_PENDING.",
            "",
            "## Synthetic scheduler-overlap probe (mean)",
            "",
            "| Stage | Milliseconds |",
            "|---|---:|",
            f"| segment→ASR | {average_latency('segment_to_asr_ms'):.3f} |",
            f"| ASR→speakers | {average_latency('asr_to_speakers_ms'):.3f} |",
            f"| speakers→facts | {average_latency('speakers_to_facts_ms'):.3f} |",
            f"| facts→hypothesis | {average_latency('facts_to_hypothesis_ms'):.3f} |",
            f"| confirmation→DIAO | {average_latency('confirmation_to_diao_ms'):.3f} |",
            f"| DIAO→watch | {average_latency('diao_to_watch_ms'):.3f} |",
            f"| end-to-end | {average_latency('end_to_end_ms'):.3f} |",
            "",
            "These values measure only the deterministic scheduler-overlap fixture with configured sleeps; they are not model, network, wearable or end-to-end latency.",
            "The complete local evidence package is under `mvp/evidence/autonomous_scenarios/` and is intentionally ignored by Git.",
            "",
        ]
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")


def _write_json(path: Path, value: dict | list) -> None:
    path.write_text(json.dumps(value, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def write_scenario_package(root: Path, scenario: dict, result: dict, audio_root: Path) -> None:
    """Persist an auditable synthetic package without duplicating generated WAVs."""
    destination = root / scenario["scenario_id"]
    destination.mkdir(parents=True, exist_ok=True)
    audio_manifest = []
    transcripts = []
    timeline = []
    assignment_by_segment = {item["segment"]: item["actual"] for item in result["assignments"]}
    role_by_segment = {item["segment"]: item["actual"] for item in result["roles"]}
    for ordinal, item in enumerate(scenario["segments"], 1):
        path = audio_root / scenario["scenario_id"] / f"{item['segment_id']}.wav"
        audio_manifest.append(
            {
                "segment_id": item["segment_id"],
                "path": path.relative_to(ROOT).as_posix(),
                "bytes": path.stat().st_size,
                "sha256": hashlib.sha256(path.read_bytes()).hexdigest().upper(),
                "generator": "offline Windows SAPI TTS",
                "synthetic": True,
            }
        )
        transcripts.append(
            {
                "segment_id": item["segment_id"],
                "speaker_ground_truth": item["speaker"],
                "speaker_cluster": assignment_by_segment[item["segment_id"]],
                "predicted_role": role_by_segment[item["segment_id"]],
                "raw_transcript_fixture": item["transcript"],
                "asr_status": "GROUND_TRUTH_FIXTURE_NOT_ASR_OUTPUT",
            }
        )
        timeline.append(
            {
                "ordinal": ordinal,
                "event": "SYNTHETIC_SEGMENT",
                "segment_id": item["segment_id"],
                "speaker": item["speaker"],
            }
        )
    timeline.extend({"event": item["action"], **item} for item in result["wearable_events"])
    history = {
        "classification": "SYNTHETIC_AUTONOMOUS_TEST_ONLY",
        "occurrence_id": scenario["scenario_id"],
        "people_and_interlocutors": result["assignments"],
        "declarations": transcripts,
        "facts": result["facts"],
        "relations": [],
        "contradictions": result["contradictions"],
        "information_gaps": scenario.get("expected_information_gaps", []),
        "hypotheses": [result["hypothesis"]],
        "officer_confirmations": [
            item for item in result["wearable_events"] if item["action"] in {"CONFIRM", "REJECT"}
        ],
        "diao_references": result["guidance"].get("sources", []),
        "actions": [item for item in result["wearable_events"] if item["action"] == "ACTION_DONE"],
        "pending": [],
        "timeline": timeline,
        "preliminary_narrative": " ".join(item["statement"] for item in result["facts"]),
        "hallucinated_fact_count": result["fact_metrics"]["hallucinated_count"],
    }
    _write_json(destination / "ground_truth.json", scenario)
    _write_json(destination / "audio_manifest.json", audio_manifest)
    _write_json(destination / "transcripts.json", transcripts)
    _write_json(destination / "speaker_assignments.json", result["assignments"])
    _write_json(destination / "embedding_metrics.json", {
        "threshold": result["speaker_threshold"],
        "calibration": result["speaker_calibration"],
        "metrics": result["speaker_metrics"],
    })
    _write_json(destination / "roles.json", result["roles"])
    _write_json(destination / "facts.json", result["facts"])
    _write_json(destination / "hypothesis.json", result["hypothesis"])
    _write_json(destination / "diao_references.json", result["guidance"])
    _write_json(destination / "watch_events.json", result["wearable_events"])
    _write_json(destination / "timeline.json", timeline)
    _write_json(destination / "HISTORICO_PRELIMINAR.json", history)
    lines = [
        f"# HISTÓRICO PRELIMINAR — {scenario['scenario_id']}", "",
        "**CENÁRIO SINTÉTICO AUTÔNOMO; NÃO É OCORRÊNCIA REAL.**", "",
        f"- Interlocutores esperados/detectados: {result['speaker_metrics']['expected']}/"
        f"{result['speaker_metrics']['detected']}",
        f"- Hipótese operacional confirmada na simulação: {result['hypothesis']['label']}",
        f"- Reavaliação necessária: {'SIM' if result['reassessment_required'] else 'NÃO'}", "",
        "## Fatos rastreáveis", "",
    ]
    lines.extend(
        f"- {item['statement']} (origem: {', '.join(item['source_segments'])})"
        for item in result["facts"]
    )
    lines.extend(["", "## Divergências", ""])
    lines.extend(f"- {item}" for item in result["contradictions"] or ["Nenhuma detectada."])
    lines.extend(["", "## Referências DIAO", ""])
    for source in result["guidance"].get("sources", []):
        section = source.get("section") or {}
        page = source.get("page") or {}
        section_label = section.get("id") if isinstance(section, dict) else section
        page_label = page.get("pdf") if isinstance(page, dict) else page
        lines.append(f"- {source['chunk_id']} — seção {section_label} — página PDF {page_label}")
    lines.extend(["", "## Narrativa preliminar", "", history["preliminary_narrative"], ""])
    (destination / "HISTORICO_PRELIMINAR.md").write_text("\n".join(lines), encoding="utf-8")


async def async_main(args) -> int:
    manifest = json.loads(args.manifest.read_text(encoding="utf-8"))
    provider = load_diao_provider(args.diao_index)
    scenarios = [await run_scenario(item, args.audio_root, provider) for item in manifest["scenarios"]]
    result = {
        "generated_at": utc_now(),
        "synthetic_only": True,
        "diao_provider_available": provider is not None,
        "scenarios": scenarios,
        "pass": all(item["pass"] for item in scenarios),
        "acceptance_scope": "FIXTURE_ORCHESTRATION_ONLY",
        "full_operational_chain_pass": False,
        "full_operational_chain_blocker": "MULTI_SPEAKER_DIARIZATION_AND_PHYSICAL_DEPLOYMENT_PENDING",
    }
    args.evidence.mkdir(parents=True, exist_ok=True)
    (args.evidence / "autonomous_scenarios.json").write_text(
        json.dumps(result, ensure_ascii=False, indent=2), encoding="utf-8"
    )
    write_report(args.report, result)
    by_id = {item["scenario_id"]: item for item in manifest["scenarios"]}
    for item in scenarios:
        write_scenario_package(args.evidence, by_id[item["scenario_id"]], item, args.audio_root)
        print(
            f"FIXTURE_{'PASS' if item['pass'] else 'FAIL'} {item['scenario_id']} "
            f"speakers={item['speaker_metrics']['expected']}/{item['speaker_metrics']['detected']} "
            f"reid={item['speaker_metrics']['reidentification_accuracy']:.3f} "
            f"roles={item['role_accuracy']:.3f} facts={item['fact_metrics']['precision']:.3f}/"
            f"{item['fact_metrics']['recall']:.3f} diao={item['guidance']['status']}"
        )
    return 0 if result["pass"] else 1


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    parser.add_argument("--audio-root", type=Path, default=DEFAULT_AUDIO)
    parser.add_argument("--diao-index", type=Path, default=ROOT / "knowledge" / "diao" / "index")
    parser.add_argument("--evidence", type=Path, default=DEFAULT_EVIDENCE)
    parser.add_argument(
        "--report", type=Path,
        default=ROOT / "docs" / "mvp_operational" / "AUTONOMOUS_TEST_REPORT.md",
    )
    return asyncio.run(async_main(parser.parse_args()))


if __name__ == "__main__":
    raise SystemExit(main())
