"""Desktop review UI. Tokenless browser bootstrap uses an existing Core credential."""
import json


def review_html(occurrence_id: str, csrf: str) -> bytes:
    settings = json.dumps({'occurrence_id': occurrence_id, 'csrf': csrf}).replace('<', '\\u003c')
    return ('''<!doctype html><html lang="pt-BR"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>SAFE-FIELD · Revisão do atendimento</title><style>
:root{color-scheme:dark}body{margin:0;background:#0c141e;color:#e8f3ff;font:17px system-ui}main{max-width:1100px;margin:auto;padding:30px}h1{color:#6ae4c5}h2{font-size:22px}section{background:#142333;border:1px solid #304453;border-radius:12px;padding:20px;margin:18px 0}button{padding:12px 18px;margin:6px;border:0;border-radius:6px;background:#93e4d0;color:#04191a;cursor:pointer}input,select,textarea{background:#091722;color:#fff;border:1px solid #597081;padding:10px;margin:4px;border-radius:4px}textarea{box-sizing:border-box;width:100%;min-height:380px;font:16px/1.55 system-ui}pre{white-space:pre-wrap;overflow-wrap:anywhere}audio{width:100%}.warning{color:#ffc480}.muted{color:#a1b4c3}a{color:#78daed}.row{padding:12px 0;border-bottom:1px solid #364250}.badge{color:#91dbfb}.error{color:#ffaeaa}button:disabled{opacity:.45;cursor:default}
</style><main><h1>SAFE-FIELD — Revisar participantes e relato</h1><p id="id"></p><p id="notice" class="warning">Carregando registros preservados…</p>
<section><h2>1. Escutar e conferir</h2><audio id="audio" controls></audio><div id="transcripts"></div></section>
<section><h2>2. Validar participantes e falas</h2><p class="muted">Selecione os IDs que o policial verificou pertencerem à mesma pessoa. Não há fusão acústica automática. É possível manter um participante sem identidade civil.</p><div id="speakers"></div><input id="name" placeholder="Nome conferido pelo policial"><select id="role"><option value="">Papel não informado</option><option>POLICE_OFFICER</option><option>REQUESTER</option><option>VICTIM</option><option>WITNESS</option><option>REPORTED_PERSON</option></select><p><button id="confirm">Confirmar / corrigir associação</button><button id="unknown">Manter não identificado</button></p><details><summary>Pistas verbais, decisões e pendências</summary><pre id="identity"></pre></details></section>
<section><h2>3. Análise preservada</h2><p class="muted">Hipóteses a avaliar; não são decisão de culpa. Orientações abaixo vêm dos registros, não são criadas pela página.</p><pre id="analysis"></pre></section>
<section><h2>4. Revisar a minuta</h2><p class="warning">Confira as atribuições, a qualificação e o relato. Providências sugeridas não podem ser descritas como realizadas.</p><textarea id="draft" aria-label="Minuta para revisão"></textarea><p><label><input id="reviewed" type="checkbox">Conferi esta versão do texto e as atribuições necessárias.</label></p><p><label><input id="limitations" type="checkbox">Conferi as pendências técnicas listadas e mantive as limitações no relato revisado, quando existirem.</label></p><button id="save">Salvar versão revisada para encaminhamento manual</button><p id="download"></p><p class="muted">O original permanece preservado. Este sistema não envia o documento à DP.</p></section><button id="refresh">Atualizar registros (preserva edição na caixa de texto)</button>
<script>
const cfg=__SETTINGS__;let data=null;let edited=false;let busy=false;const el=id=>document.getElementById(id);const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
el('id').textContent=cfg.occurrence_id;el('audio').src='/demo/audio/'+encodeURIComponent(cfg.occurrence_id);
async function request(path,payload){const r=await fetch('/review/'+path,{method:payload?'POST':'GET',credentials:'same-origin',headers:payload?{'Content-Type':'application/json','X-Review-CSRF':cfg.csrf}:{},body:payload?JSON.stringify(payload):undefined});const v=await r.json();if(!r.ok)throw new Error(v.detail||v.error||('HTTP '+r.status));return v;}
function render(v){data=v;const ir=v.identity_review;el('notice').textContent=ir.pending_count?'Existem '+ir.pending_count+' pendências de atribuição. A análise não foi apagada.':'Atribuições revisadas. Confira agora o texto integral.';el('transcripts').innerHTML=v.transcripts.map(t=>'<div class="row"><b>'+esc(t.segment_id)+' · '+esc((t.speaker_ids||[]).join(', '))+'</b><p>'+esc(t.raw_transcript)+'</p></div>').join('');el('speakers').innerHTML=ir.known_speaker_ids.map(s=>'<label class="row" style="display:block"><input type="checkbox" name="sid" value="'+esc(s)+'"> '+esc(s)+' — '+esc(ir.confirmed_identity_by_speaker[s]||(ir.decisions_by_speaker[s]?'mantido não identificado':'PENDENTE'))+'</label>').join('');el('identity').textContent=JSON.stringify(ir,null,2);el('analysis').textContent=JSON.stringify({facts:v.facts,hipoteses:v.hypotheses,lacunas:v.gaps,divergencias:v.divergences,orientacoes:v.guidance,erros:v.processing_errors,cobertura:v.coverage},null,2);if(!edited)el('draft').value=v.draft_text;el('save').disabled=!ir.report_finalization_allowed;}
async function action(fn){if(busy)return;busy=true;try{await fn()}catch(e){el('notice').textContent=e.message;el('notice').className='error'}finally{busy=false}}
async function load(){render(await request('state'));}
async function decide(keep){const ids=[...document.querySelectorAll('input[name=sid]:checked')].map(x=>x.value);if(!ids.length)throw new Error('Selecione pelo menos um ID de falante.');const cues=data.identity_review.identity_cues.filter(c=>(c.candidate_speaker_ids||[]).length===1&&ids.includes(c.candidate_speaker_ids[0])).map(c=>c.cue_id);const v=await request('identity',{speaker_ids:ids,identity:el('name').value,role:el('role').value||null,cue_ids:cues,decision:keep?'KEEP_UNIDENTIFIED':'CONFIRM_IDENTITY',source_revision:data.source_revision});el('reviewed').checked=false;render(v.review);}
el('confirm').onclick=()=>action(()=>decide(false));el('unknown').onclick=()=>action(()=>decide(true));el('refresh').onclick=()=>action(load);el('draft').oninput=()=>{edited=true;el('reviewed').checked=false;};el('save').onclick=()=>action(async()=>{const v=await request('finalize',{source_revision:data.source_revision,text:el('draft').value,reviewed:el('reviewed').checked,acknowledge_limitations:el('limitations').checked});const a=document.createElement('a');a.href='/review/document/'+encodeURIComponent(v.document.document_id);a.textContent='Baixar versão revisada · '+v.document.document_id;a.download=v.document.file;el('download').replaceChildren(a);el('notice').textContent='Versão revisada salva. Envio à DP NÃO realizado.';});action(load);
</script></main></html>''').replace('__SETTINGS__',settings).encode('utf-8')
