`timescale 1ns/1ps
module safe_field_tp5_top #(parameter integer POR_BITS=8,parameter integer HALF_PERIOD_CLKS=5,parameter integer WINDOW_LOG2=8,parameter[23:0]THRESHOLD_ON=24'd12000,parameter[23:0]THRESHOLD_OFF=24'd6000,parameter integer ATTACK_WINDOWS=24,parameter integer RELEASE_WINDOWS=82,parameter integer UART_CLKS_PER_BIT=234)(input wire sys_clk,input wire pi_signal,input wire i2s_sd,input wire uart_rx,output wire i2s_sck,output wire i2s_ws,output wire led,output wire uart_tx);
reg[POR_BITS-1:0]por_counter={POR_BITS{1'b0}};reg reset_n=1'b0;always@(posedge sys_clk)begin if(&por_counter)reset_n<=1'b1;else begin por_counter<=por_counter+1'b1;reset_n<=1'b0;end end
wire capture_strobe;wire[5:0]capture_bit_index;wire signed[23:0]sample_data;wire sample_valid,sample_channel,i2s_frame_error;wire[23:0]magnitude;wire frame_valid;wire[23:0]energy;wire sound_active;
i2s_clock_gen #(.HALF_PERIOD_CLKS(HALF_PERIOD_CLKS))clkgen(.clk(sys_clk),.reset_n(reset_n),.i2s_sck(i2s_sck),.i2s_ws(i2s_ws),.capture_strobe(capture_strobe),.capture_bit_index(capture_bit_index));
i2s_rx_24 i2srx(.clk(sys_clk),.reset_n(reset_n),.capture_strobe(capture_strobe),.capture_bit_index(capture_bit_index),.serial_data(i2s_sd),.sample_data(sample_data),.sample_valid(sample_valid),.sample_channel(sample_channel),.frame_error(i2s_frame_error));
audio_energy_detector #(.WINDOW_LOG2(WINDOW_LOG2),.THRESHOLD_ON(THRESHOLD_ON),.THRESHOLD_OFF(THRESHOLD_OFF),.ATTACK_WINDOWS(ATTACK_WINDOWS),.RELEASE_WINDOWS(RELEASE_WINDOWS))energy0(.clk(sys_clk),.reset_n(reset_n),.sample_data(sample_data),.sample_valid(sample_valid),.sample_channel(sample_channel),.magnitude(magnitude),.frame_valid(frame_valid),.energy(energy),.sound_active(sound_active));
wire command_valid,command_ready;wire[7:0]command_id;wire[15:0]command_sequence;wire[31:0]command_payload;wire checksum_error,framing_error;reg response_pending;reg[7:0]response_type;reg[15:0]response_sequence;reg[31:0]response_data;reg[7:0]response_flags;wire telemetry_ready,telemetry_busy;assign command_ready=!response_pending;
sf_command_rx #(.UART_CLKS_PER_BIT(UART_CLKS_PER_BIT))cmdrx(.clk(sys_clk),.reset_n(reset_n),.uart_rx(uart_rx),.command_ready(command_ready),.command_valid(command_valid),.command_id(command_id),.command_sequence(command_sequence),.command_payload(command_payload),.checksum_error(checksum_error),.framing_error(framing_error));
wire signed[31:0]q15_result;wire q15_sat;sf_fixed_q15_mac q15(.a_q15(command_payload[31:16]),.b_q15(command_payload[15:0]),.acc_q15(32'sd0),.result_q15(q15_result),.saturated(q15_sat));
wire[15:0]fp16_result;wire fp_invalid,fp_overflow,fp_underflow;sf_fp16_mul fp16(.a(command_payload[31:16]),.b(command_payload[15:0]),.result(fp16_result),.invalid(fp_invalid),.overflow(fp_overflow),.underflow(fp_underflow));
reg[31:0]good_commands,crc_errors,framing_errors;reg frame_error_latched;
always@(posedge sys_clk or negedge reset_n)begin if(!reset_n)begin response_pending<=0;response_type<=0;response_sequence<=0;response_data<=0;response_flags<=0;good_commands<=0;crc_errors<=0;framing_errors<=0;frame_error_latched<=0;end else begin if(checksum_error)crc_errors<=crc_errors+1'b1;if(framing_error)framing_errors<=framing_errors+1'b1;if(i2s_frame_error)frame_error_latched<=1'b1;if(response_pending&&telemetry_ready)response_pending<=1'b0;if(command_valid&&command_ready)begin good_commands<=good_commands+1'b1;response_pending<=1'b1;response_type<=command_id;response_sequence<=command_sequence;response_flags<={1'b0,frame_error_latched,1'b0,q15_sat,fp_invalid,fp_overflow,fp_underflow,sound_active};case(command_id)8'h01:response_data<=32'h54503501;8'h10:response_data<=q15_result;8'h11:response_data<={16'd0,fp16_result};8'h20:response_data<=good_commands+1'b1;8'h21:response_data<={8'd0,energy};8'h22:response_data<=crc_errors;8'h23:response_data<=framing_errors;default:begin response_data<=32'hFFFFFFFF;response_flags[7]<=1'b1;end endcase end end end
sf_telemetry_tx #(.UART_CLKS_PER_BIT(UART_CLKS_PER_BIT))txframe(.clk(sys_clk),.reset_n(reset_n),.event_valid(response_pending),.event_ready(telemetry_ready),.event_type(response_type),.event_sequence(response_sequence),.event_data(response_data),.event_flags(response_flags),.uart_tx(uart_tx),.busy(telemetry_busy));
assign led=pi_signal|sound_active;
endmodule
